name = "padconnect-receiver"
product-name = "PadConnectReceiver"
identifier = "io.github.padconnectreceiver"
version = "1.0.0-rc1"
formats = ["nsis"]
binaries = [
  { path = "PadConnectReceiver", main = true }
]
out-dir = "target/release"
before-packaging-command = "cargo build --release"

[nsis]
installerIcon = "icons/icon.ico"
installMode = "perMachine"